# Docmost container configuration
version: '3.8'

services:
  docmost:
    image: docker.io/docmost/docmost:latest
    container_name: docmost-server
    environment:
      APP_URL: 'http://localhost:24012'
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: 'redis://redis:6379'
      MULTI_SPACE: 'true'
    ports:
      - '24012:3000'
    restart: unless-stopped
    volumes:
      - ./data:/app/data/storage:Z
      - ./backups:/backups:Z
    networks:
      - db_stack
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:7.2-alpine
    container_name: docmost-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data:Z
    networks:
      - db_stack

networks:
  db_stack:
    external: true

# add make permissions for volumes
# sudo chmod -R 777 docmost