# Lamp use podman-compose.yml
version: "3.8"

services:
  apache:
    image: php:8.2-apache
    container_name: lamp-apache
    ports:
      - "5050:80"
    volumes:
      - /home/abdulwahab/Containers/lamp/www:/var/www/html:Z
    depends_on:
      - db

  db:
    image: docker.io/library/mariadb:latest
    ports:
      - "3306:3306"
    container_name: lamp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql:Z
      - /home/abdulwahab/Containers/lamp/init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass
      UPLOAD_LIMIT: 520M
