version: "3.8"

services:
  adminer:
    image: docker.io/adminer:latest
    container_name: adminer-server
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: ${MARIADB_HOST:-mariadb}
      ADMINER_PORT: ${MARIADB_INTERNAL_PORT:-3306}
    ports:
      - "${ADMINER_PORT:-24002}:8080"
    networks:
      - db_stack

networks:
  db_stack:
    external: true
