version: "3.8"

services:
  mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: mariadb-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT:-24001}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
      - ./backups:/backups:Z
    networks:
      - db_stack

networks:
  db_stack:
    external: true
