version: "3.9"

services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer-server
    ports:
      - "24000:9000" # HTTP UI
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - ./portainer_data:/data

volumes:
  portainer_data:
