version: "3.8"
services:
  mariadb:
    image: docker.io/library/mariadb:latest
    container_name: database-mariadb
    restart: always
    ports:
      - "3310:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123
    volumes:
      - /home/abdulwahab/Containers/mysql/data:/var/lib/mysql:Z

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    container_name: database-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
      MAX_EXECUTION_TIME: 300 
    ports:
      - "5051:80"
    depends_on:
      - mariadb

  # adminer:
  #   image: docker.io/library/adminer:latest
  #   container_name: database-adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mariadb
  #   ports:
  #     - "5052:8080"
  #   depends_on:
  #     - mariadb
